services:
  web:
    build: .
    container_name: tommy_game_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_NAME=tommy_game_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app # Link the local code into the container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # Enable reolad during development

  db:
    image: postgres:15
    container_name: tommy_game_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tommy_game_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
